name: 'Sign up apk'
description: 'Generating keys, aligning apk and signing up it'
inputs:
  apk-path:
    description: 'Path to apk'
    required: true
  apk-unsigned-filename:
    description: 'Name of unsigned release apk file'
    required: true
  apk-signed-filename:
    description: 'Name of signed release apk file'
    required: true
  base64-key:
    description: 'Key in base64'
    required: true
  store-password:
    description: 'Store password for keytool (the same as key password)'
    required: true
  key-alias:
    description: 'Key alias for keytool'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up zipalign
      uses: ./.github/actions/set-up-zipalign
    - name: Align apk
      working-directory: ${{ inputs.apk-path }}
      run: zipalign -v -p 4 ${{ inputs.apk-unsigned-filename }} app-release-unsigned-aligned.apk
      shell: bash
    - name: Set up apksigner
      uses: ./.github/actions/set-up-apksigner
    - name: Restore keystore from GitHub Secrets
      working-directory: ${{ inputs.apk-path }}
      run: echo "${{ inputs.base64-key }}" | base64 --decode > android-release-key.jks
      shell: bash
    - name: Sign apk with existing keys
      working-directory: ${{ inputs.apk-path }}
      run: |
        apksigner sign \
          --ks android-release-key.jks \
          --ks-pass pass:${{ inputs.store-password }} \
          --key-pass pass:${{ inputs.store-password }} \
          --ks-key-alias ${{ inputs.key-alias }} \
          --out ${{ inputs.apk-signed-filename }} \
          app-release-unsigned-aligned.apk
      shell: bash
    - name: Verify apk
      working-directory: ${{ inputs.apk-path }}
      run: apksigner verify --print-certs ${{ inputs.apk-signed-filename }}
      shell: bash
