name: How Do You Feel

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['develop']
  push:
    branches: ['develop']

env:
  NODE_MODULES_PATH: "./node_modules"
  JDK_VERSION: 21
  RELEASE_APK_PATH: ./android/app/build/outputs/apk/release
  UNSIGNED_RELEASE_APK_FILENAME: app-release-unsigned.apk
  SIGNED_RELEASE_APK_FILENAME: how-do-you-feel-release.apk

jobs:
  create-cache-key:
    name: Create cache key
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.create-cache-key.outputs.key }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Output cache key
        id: create-cache-key
        run: echo "key=${{ github.repository }}-${{ github.ref }}-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT

  cache-deps:
    name: Cache dependencies
    needs: [create-cache-key]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Cache (save) node modules
        uses: actions/cache/save@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"

  lint:
    name: Run lint
    needs: [create-cache-key, cache-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run lint
        run: npm run lint

  stylelint:
    name: Run stylelint
    needs: [create-cache-key, cache-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run lint
        run: npm run stylelint

  build:
    name: Run build
    needs: [create-cache-key, lint, stylelint]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run web:build
        run: npm run web:build

  build-apk:
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Set up Open JDK 21
      uses: ./.github/actions/set-up-openjdk
      with:
        version: ${{ env.JDK_VERSION }}
    - name: Get dependencies
      run: npm ci --legacy-peer-deps
    - name: Run web:build
      run: npm run web:build
    - name: Run android:sync
      run: npm run android:sync
    - name: Build apk file
      working-directory: ./android
      run: ./gradlew assembleRelease
    - name: Sign up apk file
      uses: ./.github/actions/sign-up-apk
      with:
        apk-path: ${{ env.RELEASE_APK_PATH }}
        apk-unsigned-filename: ${{ env.UNSIGNED_RELEASE_APK_FILENAME }}
        apk-signed-filename: ${{ env.SIGNED_RELEASE_APK_FILENAME }}
        store-password: ${{ secrets.STORE_PASSWORD }}
    - name: Create artifact with apk
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref }}-commit file
        path: ${{ env.SIGNED_RELEASE_APK_FILENAME }}
    # - name: Save package.json version
    #   id: version
    #   # Обрезаем версию по бокам на один символ, тк npm pkg get version возвращает строку
    #   run: VERSION_STR=$(npm pkg get version) && echo "VERSION=${VERSION_STR:1:-1}" >> $GITHUB_OUTPUT
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.version.outputs.VERSION }}
    #     release_name: Release ${{ steps.version.outputs.VERSION }}
    #     body_path: ./apps/mobile/CHANGELOG.md
    #     draft: false
    #     prerelease: true
    # - name: Upload Release Artifact
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ${{ env.RELEASE_APK_PATH }}/${{ env.SIGNED_RELEASE_APK_FILENAME }}
    #     asset_name: ${{ env.SIGNED_RELEASE_APK_FILENAME }}
    #     asset_content_type: application/vnd.android.package-archive
