name: How Do You Feel

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['develop']
  push:
    branches: ['develop']

env:
  NODE_MODULES_PATH: "./node_modules"
  JDK_VERSION: 21
  RELEASE_APK_PATH: "./android/app/build/outputs/apk/release"
  UNSIGNED_RELEASE_APK_FILENAME: "app-release-unsigned.apk"
  SIGNED_RELEASE_APK_FILENAME: "how-do-you-feel-release.apk"

  DOWNLOAD_ARTEFACT_PATH: "./artifacts/apk"
  DOWNLOAD_ARTEFACT_NAME: "Release apk"
  RELEASE_ARCHIVE_NAME: "how-do-you-feel.tar.gz"

jobs:
  create-cache-key:
    name: Create cache key
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.create-cache-key.outputs.key }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Output cache key
        id: create-cache-key
        run: echo "key=${{ github.repository }}-${{ github.ref }}-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT

  cache-deps:
    name: Cache dependencies
    needs: [create-cache-key]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Cache (save) node modules
        uses: actions/cache/save@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"

  lint:
    name: Run lint
    needs: [create-cache-key, cache-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run lint
        run: npm run lint

  stylelint:
    name: Run stylelint
    needs: [create-cache-key, cache-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run lint
        run: npm run stylelint

  analyze-deps:
    name: Run analyze deps
    needs: [create-cache-key, cache-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Make directory "deps"
        run: mkdir deps
      - name: Run analyze:deps
        run: npm run analyze:deps
      - name: Get short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
      - name: Create artifact with apk
        uses: actions/upload-artifact@v4
        with:
          name: "Dependency Graph for ${{ steps.short-sha.outputs.sha }}"
          path: deps/graph.png

  build:
    name: Run build
    needs: [create-cache-key, lint, stylelint, analyze-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: "${{ needs.create-cache-key.outputs.cache-key }}"
          fail-on-cache-miss: true
      - name: Run web:build
        run: npm run web:build

  build-apk:
    needs: [create-cache-key, build]
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Restore node modules
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.NODE_MODULES_PATH }}
        key: "${{ needs.create-cache-key.outputs.cache-key }}"
        fail-on-cache-miss: true
    - name: Set up Open JDK 21
      uses: ./.github/actions/set-up-openjdk
      with:
        version: ${{ env.JDK_VERSION }}
    - name: Run web:build
      run: npm run web:build
    - name: Run android:sync
      run: npm run android:sync
    - name: Build apk file
      working-directory: ./android
      run: ./gradlew assembleRelease
    - name: Get short SHA
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
    - name: Sign up apk file
      uses: ./.github/actions/sign-up-apk
      with:
        apk-path: ${{ env.RELEASE_APK_PATH }}
        apk-unsigned-filename: ${{ env.UNSIGNED_RELEASE_APK_FILENAME }}
        apk-signed-filename: "how-do-you-feel.${{ steps.short-sha.outputs.sha }}.apk"
        store-password: ${{ secrets.STORE_PASSWORD }}
    - name: Create artifact with apk
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DOWNLOAD_ARTEFACT_NAME }}
        path: "${{ env.RELEASE_APK_PATH }}/how-do-you-feel.${{ steps.short-sha.outputs.sha }}.apk"
        retention-days: 7

  build-release-version:
    # if: github.event_name == 'push' && github.ref_name == 'develop'
    needs: [build-apk]
    name: Build version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create-release-version.outputs.VERSION }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Save package.json version
        id: create-release-version
        # Обрезаем версию по бокам на один символ, тк npm pkg get version возвращает строку
        run: VERSION_STR=$(npm pkg get version) && echo "VERSION=${VERSION_STR:1:-1}" >> $GITHUB_OUTPUT

  create-release:
    # if: github.event_name == 'push' && github.ref_name == 'develop'
    needs: [build-release-version]
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DOWNLOAD_ARTEFACT_NAME }}
          path: ${{ env.DOWNLOAD_ARTEFACT_PATH }}
      - name: Make archive
        run: tar -czvf ${{ env.RELEASE_ARCHIVE_NAME }} -C ${{ env.DOWNLOAD_ARTEFACT_PATH }} .
      - name: Make Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build-release-version.outputs.version }}
          name: Release ${{ needs.build-release-version.outputs.version }}
          body_path: ./README.md
          files: ${{ env.RELEASE_ARCHIVE_NAME }}
          draft: false
          prerelease: false


